apiVersion: v1
kind: LimitRange
metadata:
  name: limite-container
spec:
  limits:
    - max:
        cpu: "200m"
        memory: "512Mi"
      min:
        cpu: "25m"
        memory: "32Mi"
      default:
        cpu: "100m"
        memory: "128Mi"
      defaultRequest:
        cpu: "75m"
        memory: "40Mi"
      type: Container          