apiVersion: v1
kind: Service
metadata:
  name: sistema-deployment
spec:
  selector:
    app: sistema
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  type: NodePort      
