apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-deployment
spec:
  selector:
    matchLabels:
     app: sistema
  template:
    metadata:
     labels:
        app: sistema
    spec:
      containers:
      - name: sistema
        image: mongo:4.2.8
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongouser
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongopwd    